apiVersion: apps/v1
kind: Deployment
metadata:
  name: datenblatt-editor
spec:
  replicas: 1
  selector:
    matchLabels: {app: datenblatt-editor}
  template:
    metadata:
      labels: {app: datenblatt-editor}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: editor
          image: sogis/datenportal-datenblatt-editor:0.1.4
          ports:
            - {name: http, containerPort: 8080}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {drop: [ALL]}
          resources:
            requests: {cpu: 25m, memory: 32Mi}
            limits: {cpu: 500m, memory: 128Mi}
          readinessProbe:
            httpGet: {path: /, port: http}
          livenessProbe:
            httpGet: {path: /, port: http}
          volumeMounts:
            - {name: tmp, mountPath: /tmp}
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: datenblatt-editor
spec:
  selector: {app: datenblatt-editor}
  ports:
    - {name: http, port: 8080, targetPort: http}
