apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sodata.yaml
  - editor.yaml
  - jenkins.yaml
  - apisix.yaml
configMapGenerator:
  - name: apisix-config
    files:
      - config.yaml=apisix/config.yaml
      - apisix.yaml=apisix/apisix.yaml
  - name: jenkins-casc
    files:
      - jenkins.yaml=jenkins/jenkins.yaml
